### ISSUE TITLE
Make doesn't work.

### ISSUE THREAD

**Issue by alexander-hamme** [digitalbrain79/pyyolo#35]
I have all options set to 0 at the top of the Makefile (GPU, CUDNN, OpenCV), and when I try to run make I get the following error:

`gcc  -Wall -Wfatal-errors -Wno-unused-result -fPIC -I./darknet/src -I./darknet/include -Ofast -c libyolo.c -o obj/libyolo.o`
`libyolo.c:5:10: fatal error: option_list.h: No such file or directory`
`#include "option_list.h"`
`          ^~~~~~~~~~~~~~~`
`compilation terminated.`
`Makefile:63: recipe for target 'obj/libyolo.o' failed`
`make: *** [obj/libyolo.o] Error 1`

**Comment by alexander-hamme** [comment]
No, not yet unfortunately...

**Comment by alexander-hamme** [comment]
No, not yet unfortunately...

**Comment by masszhou** [comment]
you need to checkout sub module for darknet
something like
git clone --recurse-submodules https://github.com/digitalbrain79/pyyolo.git

**Comment by alexander-hamme** [comment]
That worked.

I already got darknet working through Python a while ago, using the native python functions pjreddie provides, but thought I'd check this out again too.

**Comment by sirinferhat** [comment]
Hello alexander-hamme,
I got the same error today. What should i do to solve this problem?

**Comment by sirinferhat** [comment]
C:\Program Files\MATLAB\R2018a\bin\yolomex>make
gcc  -DGPU -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -DCUDNN  -Wall -Wfatal-errors -Wno-unused-result -fPIC -I./yolomex/darknet/src -I./yolomex/darknet/include -Ofast -DGPU -DCUDNN -c libyolo.c -o obj/libyolo.o
libyolo.c:5:10: fatal error: option_list.h: No such file or directory
 #include "option_list.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [obj/libyolo.o]
